name: nice_and_healthy
description: "E-shop with beauty and health products"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ^3.24.1

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_layout_grid: 2.0.7
  flutter_rating_bar: 4.0.1
  flutter_riverpod: 2.5.1
  go_router: 14.2.7
  intl: 0.19.0
  path_provider: 2.1.4
  riverpod: 2.5.1
  rxdart: 0.28.0
  sembast: 3.7.3
  sembast_web: 2.4.0

dev_dependencies:
  custom_lint: 0.6.5
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 1.0.4
  riverpod_lint: 2.3.13
  strict: 2.1.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/common/app_icon.png"
  image_path_android: "assets/android/app_icon_android.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/android/app_icon_background.png"
  adaptive_icon_foreground: "assets/android/app_icon_foreground.png"
  macos:
    generate: true
    image_path: "assets/common/app_icon.png"
  web:
    generate: true
    image_path: "assets/common/app_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all product images
    - assets/products/

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
