name: nice_and_healthy
description: "E-shop with beauty and health products"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_layout_grid: 2.0.7
  flutter_rating_bar: 4.0.1
  flutter_riverpod: 2.5.1
  go_router: 14.2.1
  intl: 0.19.0
  rxdart: 0.27.7

dev_dependencies:
  custom_lint: 0.6.4
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  riverpod_lint: 2.3.10
  strict: 2.1.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/common/app_icon.png"
  image_path_android: "assets/android/app_icon_android.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/android/app_icon_background.png"
  adaptive_icon_foreground: "assets/android/app_icon_foreground.png"
  macos:
    generate: true
    image_path: "assets/common/app_icon.png"
  web:
    generate: true
    image_path: "assets/common/app_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all product images
    - assets/products/
